# Generated by Django 5.1.1 on 2024-11-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='blog_tag',
        ),
    ]
